apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcd-deployment
spec:
  selector:
    matchLabels:
      app: flux
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: fluxcd
    spec:
      containers:
      - name: fluxcd
        image: fluxcd/flux:1.24.1
        ports:
        - containerPort: 80